# Generated by Django 5.0.6 on 2024-07-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date_submitted',
        ),
    ]
